### ISSUE TITLE
UI 메인구성을 조금 바꾸어야 합니다

### ISSUE THREAD

**Issue by Cocozo** [kookmin-sw/capstone-2023-43#1]
우리 서비스의 목적 -> 복약 알림 서비스 + 추가 복약 여부 판별 서비스

하지만 플레이 그라운드에 우리가 그렸던 앱 레이아웃은 '복약' 이 아니라 '약' 에 너무 포커스 되어있습니다.
이에 내가 어떤 약을 복약하고 있는지에 대해서는 알 수 있으나, 정작 오늘, 아니 특정시일에 내가 어떤 약을 먹어야 한다는
정보에 대해 빈약하게 제공하고 있습니다.

이에 메인페이지에 '약'에대한 정보 뿐만 아니라, 내가 오늘 어떤 약을 복약해야 하는지와 같은 정보를 제공해 주어야 한다 생각하고,
다음주 중에 한번 다시 모여 UI 레이아웃에 대해 한번더 의견을 내어 바꾸어 봐야 한다 생각합니다.

**Comment by fmowl10** [comment]
이전에 따로 답변한 것과 같이 현재 작업하고 있는 뷰에서 사용자가 오늘 복용해야하는 약들을 리스트로 간단히 보여주되 약들 마다 컴포넌트를 가진 형태였으면 좋겠습니다.
품목명, 약의 효능, 먹을 시간을 간단히 띄우고 있어야 한다고 생각합니다.

**Comment by fmowl10** [comment]
추가적으로 복용이 끝나는 약은 특정한 색으로 알려주었으면 하네요.
