### ISSUE TITLE
DB 스키마에서 CamelCase를 snake_case로 바꿔주세요

### ISSUE THREAD

**Issue by whdgmawkd** [kookmin-sw/capstone-2023-43#18]
DB 만들건데 snake_case로 스키마 다시 써주세요.
그리고 ItemSeq 형식도 int로
나머지 숫자인 애들도 int로 바꿔주세요 (uint32같은것들)

maxtaboo테이블도 int두개인 걸로 해주십시요

**Comment by fmowl10** [comment]
수정하였습니다. 확인 후 닫아주세요.

**Comment by fmowl10** [comment]
728bafce06f36159e730fca5a575e297c91a1e6d 에서 수정하였습니다. 확인 부탁드립니다.

**Comment by whdgmawkd** [comment]
압도적 감사...!
