### ISSUE TITLE
데이터 가공 시 저장 방식 및 포맷

### ISSUE THREAD

**Issue by whdgmawkd** [kookmin-sw/capstone-2023-43#19]
식품의약품안전처_의약품 제품 허가정보 API를 사용할 경우
반환으로 오는 정보중에 "EE_DOC_DATA", "UD_DOC_DATA", "NB_DOC_DATA" 항목의 값이 XML형태로 되어있고, 이는 HTML을 표현하고 있음.

이를 앱에서 표시하기 위해서는 우리가 직접 데이터를 가공하는 것 보다는 WebView를 통해서 직접 보여주는게 효율적일 것같음.

이와 관련해 추가 정보 및 의견을 제시해주세요

**Comment by fmowl10** [comment]
UD_DOC_DATA(용법용량)에서 신장애 있는 환자의 용량을 계산하는 식을 테이블을 이용하여 보여주고 있음
NB_DOC_DATA(주의사항)에서는 몇몇 전문약품에서 일어나는 부작용을 테이블형태로 다루고 있음

이러한 데이터들은 모두 정형화된 형식이 없으며 때때로 ```<image>``` 태그를 가져와 이미지형태로 보여주고 있음

완전한 HTML 형식이 아니기에 HTML 형식으로 바꾸는 작업이 필요합니다.

WebVIew를 통해 보여주는 방식을 동의합니다.

**Comment by Cocozo** [comment]
flutter에서 <section>이나 <div> 와 같은 태그로 묶여있는 블록 단위로 끊어진 html 구문으로 만들어져 보내질 수 있다면 flutter에서 충분히 가공하여 사용할 수 있습니다.
따라서 html형식으로 보내어서 사용해도 무관합니다.

**Comment by whdgmawkd** [comment]
굿

**Comment by fmowl10** [comment]
https://github.com/kookmin-sw/capstone-2023-43/blob/afabc14c4c4a86ea9ebf3c184ec67dccc0d9de37/Crawler/doc_parse.py#L4 에서 해결했습니다.
