### ISSUE TITLE
스키마 설명이 모호함

### ISSUE THREAD

**Issue by whdgmawkd** [kookmin-sw/capstone-2023-43#22]
DB스키마에서 mix_taboo의 경우
item_seq와 mixture_item_seq가 있는데, 현재 설명이 애매모호 합니다

item_seq가 source고 
mixutre_item_seq가 target인데
이걸 어떻게 하면 적절하게 한글로 표현할 수 있을까요?

의견 자유롭게 내보세요

**Comment by whdgmawkd** [comment]
item_seq: 비교할 약물 품목기준코드
mixture_item_seq: 병용금기 약물 품목기준코드

**Comment by fmowl10** [comment]
> item_seq: 비교할 약물 품목기준코드 mixture_item_seq: 병용금기 약물 품목기준코드

좋은 것 같습니다.

**Comment by fmowl10** [comment]
3a7be20d3028de8c6e068355b0fd450e12fe7d04 에서 수정했습니다.

**Comment by whdgmawkd** [comment]
좋습니다
