### ISSUE TITLE
android 앱 레이아웃 깨짐

### ISSUE THREAD

**Issue by fmowl10** [kookmin-sw/capstone-2023-43#24]
![Screenshot_20230328_153511](https://user-images.githubusercontent.com/6753999/228149065-b7131197-3ae2-491e-bc65-94ba8d8ecb7d.jpg)

Web 환경에서는 앱 화면이 위처럼 깨지지 않지만, 안드로이드에 올릴 경우 기기 화면의 가로 해상도가 작아 깨집니다.

2400 x 1080 px (Galaxy A Quantum)

**Comment by Cocozo** [comment]
해결완료
