### ISSUE TITLE
GraphQL artemis로 모델 제너레이트 하면 생기는 문제

### ISSUE THREAD

**Issue by fmowl10** [kookmin-sw/capstone-2023-43#25]
스키마를 가져와서 제너레이트 한것은 좋은데 class라는 컬럼이 예약어라 우리가 원했던 컬럼 네임으로 생성되지 않아 혼동될 여지가 있습니다. 이름을 바꿔야겠습니다. 
의견받습니다.

아래와 같이 제너레이트 됩니다.

https://github.com/kookmin-sw/capstone-2023-43/blob/7f9a149fd8c6309b933d653a9c4297aca5a68ead/flutter_frontend/lib/generated/graphql_api.graphql.g.dart#L17

https://github.com/kookmin-sw/capstone-2023-43/blob/7f9a149fd8c6309b933d653a9c4297aca5a68ead/flutter_frontend/lib/generated/graphql_api.graphql.dart#L30

**Comment by whdgmawkd** [comment]
DB의 다른 칼럼도 name, entp_name으로 되어있으니
class_name이라고 이름 붙이면 class 예약어와 겹치는 문제를 해결할 수 있을것 같습니다.

**Comment by fmowl10** [comment]
일단 다이어그램 내용 수정하겠습니다. Backend 측에서도 컬럼 수정 부탁드립니다.

**Comment by whdgmawkd** [comment]
수정 완료했습니다
pb_pill_info.class -> pb_pill_info.class_name

**Comment by fmowl10** [comment]
다이어그램 수정 완료 하였습니다.
3a7be20d3028de8c6e068355b0fd450e12fe7d04
