### ISSUE TITLE
코드 freeze 및 PR 부탁드립니다.

### ISSUE THREAD

**Issue by fmowl10** [kookmin-sw/capstone-2023-43#27]
중간 발표가 다가와 여러 브랜치로 갈라져 있던 진행상황을 freeze하고 모두 머지하는 것을 부탁드립니다.
아래 해당되는 브랜치를 담당하시는 분들은 4월 5일까지 정리 및 머지를 마무리 지어 주세요.
* frontend_dev
* backend_dev
* cralwer_dev

일정 수정 요청이나 해당 사항에 논의할 내용이 있으면 코멘트 남겨주세요.

**Comment by whdgmawkd** [comment]
backend_dev와 cralwer_dev 머징완료

**Comment by Cocozo** [comment]
frontend_dev 머징 완료

**Comment by fmowl10** [comment]
모든 브랜치 PR 및 머징 완료 확인했습니다.
