### ISSUE TITLE
backend에 graphql 엔드포인트 없애고 별도 엔드포인트에서 운영

### ISSUE THREAD

**Issue by whdgmawkd** [kookmin-sw/capstone-2023-43#34]
현재 Serverless 프레임워크에서 공식지원하는 기능이 아닌지라 Cloudformation 포맷으로 작성되어 있는데 이게 배포시 오류가 나기도 합니다.

따라서 graphql은 notion에 있는 엔드포인트를 사용하도록 하고 API Gateway에서는 삭제하려고 하는데 다른사람들 의견을 취합하고자 합니다.

**Comment by fmowl10** [comment]
확인완료
hasura 고정 IP이기에 문제없을 것 같습니다.

**Comment by Cocozo** [comment]
상관없습니다. 확인 완료
