### ISSUE TITLE
약 정보페이지의 웹 정보 에 대해서( 정보량/ 스타일)

### ISSUE THREAD

**Issue by Cocozo** [kookmin-sw/capstone-2023-43#36]
현재 개발중인 약 정보 페이지에서 html 뷰를 이용해서 웹 뷰를 구현했습니다.
하지만 저희가 설계한 사이즈와 맞지않은 사이즈의 테이블이 나오기도 하고, 또한 보여주는 정보량이 너무 많아 뷰에서 제공하는 정보가 과다하게 증가하게 됩니다.
이에 CSS 설계, 또는 추가적인 액션구현이 필요합니다.
<img width="305" alt="스크린샷 2023-05-02 오후 4 18 23" src="https://user-images.githubusercontent.com/20090232/235603904-5a9657f4-a4c6-4253-8289-394c03517217.png">
<img width="322" alt="스크린샷 2023-05-02 오후 4 18 55" src="https://user-images.githubusercontent.com/20090232/235603912-f1e946c0-be73-4b5e-bcb0-0c96950fb4df.png">

**Comment by fmowl10** [comment]
1. 테이블 크기에 설정 문제
이건 우리 쪽에서 가공하기에는 문제가 있다. 
적어도 style attribute는 삭제가능하다.
3. 정보량이 많은 문제
이경우 제조사의 의도를 모두 보여줘야 하므로 가공불가
차라리 접히는 구조로 구현할 것

**Comment by fmowl10** [comment]
현재 보이는 에러가 담겨있는 의약품의 표준기준코드 : 202005623
image 태그를 가지고 있는 표준기준코드 : 199700810 
image태그는 테스트 결과 잘보여줌

**Comment by fmowl10** [comment]
람다에서 html페이지를 보여주는 방향으로 갔습니다.
