### ISSUE TITLE
우리 서비스의 대표색을 정해주세요!

### ISSUE THREAD

**Issue by Cocozo** [kookmin-sw/capstone-2023-43#4]
세상에나, 우리 어플리케이션의 대표색이 없어요!
디자인 프로토 타입을 제작중에 있는데 아직 대표적인 색상이 정해지지 않아 빠른 시일내에 컬러 팔레트 하나를 만들어 두어야 합니다!
여러가지 디자인 코멘트를 받으니 자신이 이색이 괜찮다 싶은 색을 알려주세요!

아래 프로그램을 활용해서 뽑아 주어도 됩니다~!
https://color.adobe.com/ko/create/color-wheel/?base=2&rule=Analogous&selected=2&name=%EB%82%B4%20Color%20%ED%85%8C%EB%A7%88&mode=rgb&rgbvalues=0.7234436451375761,0.9755616348744889,1,0.6583337170751943,0.91,0.8626910142488724,0.7734436451375761,1,0.8932915310696097,0.6583337170751943,0.91,0.7202384012725186,0.7360694049488107,1,0.7234436451375761&swatchOrder=0,1,2,3,4

**Comment by fmowl10** [comment]
파란색 계열로 가서 아래 5개를 추천합니다. 
#0D36FD
#0B6AE3
#00B1FA
#0BDBE3
#0DFDC2
