### ISSUE TITLE
이미지 인식에 관한 이슈

### ISSUE THREAD

**Issue by Cocozo** [kookmin-sw/capstone-2023-43#5]
우리가 약국에서 처방한 약중, 온전한 알약형태의 약이 들어있는 반면
약의 성분에 따라 약을 2등분, 4등분을 할 수 있습니다.

이와같은경우, 우리가 가지고 있는 학습 데이터 상에서의 모양과 상이하여 인식이 되지 않을 가능성이 높습니다.
따라서 이에 대해 이미지 검색에 대해 커팅된 약 또한 검색을 가능하게 할지, 아님 온전한 약만 인식을 할 수 있도록 만들어야할지
검토가 이루어 져야 한다 생각합니다
![pillImg](http://uncoveredhc.com/wp-content/uploads/2019/11/2019-11-19.jpg)

**Comment by fmowl10** [comment]
약학정보원에서 제공하는 [인공지능 개발을 위한 알약 이미지 데이터](https://www.health.kr/notice/notice_view.asp?show_idx=1001&search_value=&search_term=&paging_value=&setLine=&setCategory=)에서는 @Cocozo 가 발언한 쪼개진 알약에 대한 이미지는 제공되지 않습니다. 그러므로 완전한 약에 대한 인식만 구현하고, 사용자에게 완전한 형태의 알약을 촬영을 부탁하는 방향으로 가야할 것 같습니다. 약학정보원에서 제공되는 학습 데이터로는 불가능합니다.

학습 데이터의 특징들을 나열 하겠습니다.

## 학습 데이터로 제공되는 알약들에 대한 특징
* 국내에 등록된 약 20,000여권의 알약 중 자주 사용되는 알약 5,098 건
* 낱알의 얖뒤로 20장 씩 즉 알약 하나당 40장
* 촬영 데이터와 배경제거 이미지

**Comment by fmowl10** [comment]
따라서 우리프로젝트는 온전한 약이미지만 처리하겠습니다.
