### ISSUE TITLE
API 명세 정하기 

### ISSUE THREAD

**Issue by fmowl10** [kookmin-sw/capstone-2023-43#8]
**Is your feature request related to a problem? Please describe.**
아무리 graphql로 작성해도 api 명세를 작성해야한다고 봄

**Describe the solution you'd like**
GraphQL 인터페이스, 적합성 인터페이스, 낱알 인식 인터페이스를 정해야한다.

**Comment by whdgmawkd** [comment]
알약 정보 조회에 대해서는 Graphql 단일 Endpoint를 사용합니다.
다만 회원의 복약 정보 추가/수정/삭제에 대해서는 일반적인 RESTfull 규칙을 사용할 예정입니다.

mongoDB에 Document 형태로 저장되기 때문에 AWS Lambda에 pymongo라이브러리를 사용하여 Serverless로 작성합니다.

pillbox/users/* 형태의 URL주소를 사용하고, 세부 규칙은 이어서 논의 후 업데이트 합니다.

**Comment by fmowl10** [comment]
Notion에 명세 문서를 작성했습니다. 추후 이곳에 작성하도록 하겠습니다.

**Comment by fmowl10** [comment]
github wiki와 notion에 작성해서 추가중입니다. 현재 구현한 사항은 정리가 되었습니다. 추가사항은 나중에 올리겠습니다.

**Comment by fmowl10** [comment]
명세 작성완료
